server:
  port: 7081
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 10000
            response-timeout: 70s
          routes:
            - id: ticket-service
              uri: "http://localhost:7071/"
              predicates:
                - Path=/ticket/* , /v3/api-docs/ticket
              filters:
                - name: CircuitBreaker
                  args:
                    name: ticketBreaker
                    fallbackUri: forward:/fb/ticket/
            - id: reservation-service
              uri: "http://localhost:7061/"
              predicates:
                - Path=/reservation/* , /v3/api-docs/reservation
              filters:
                - name: CircuitBreaker
                  args:
                    name: reservationBreaker
                    fallbackUri: forward:/fb/reservation/
            - id: user-service
              uri: "http://localhost:7051/"
              predicates:
                - Path=/user/* , /v3/api-docs/user
              filters:
                - name: CircuitBreaker
                  args:
                    name: userBreaker
                    fallbackUri: forward:/fb/user/
    discovery:
      locator:
        enabled: true

resilience4j:
  time limiter:
    configs:
      default:
        timeoutDuration: 7000
        cancelRunningFuture: true

logging:
  level:
    org:
      springframework:
        cloud.gateway: DEBUG
        http.server.reactive: DEBUG
        web.reactive: DEBUG

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
